/**
 * Level Data Types
 * Defines the structure of level configurations
 */

// Object types that can be placed in a level
export type ObjectType = 
  | 'rail'
  | 'rail_angled'
  | 'rail_curved'
  | 'ramp'
  | 'quarter_pipe'
  | 'quarter_pipe_small'
  | 'quarter_pipe_med'
  | 'quarter_pipe_large'
  | 'half_pipe'
  | 'fun_box'
  | 'stairs'
  | 'platform'
  | 'wall'
  | 'desk'
  | 'cubicle'
  | 'water_cooler'
  | 'elevator'
  | 'escalator'
  | 'planter'
  | 'car'
  | 'bench'
  | 'trash_can'
  | 'cone'
  | 'barrier'
  | 'building'
  | 'building_small'
  | 'building_medium'
  | 'building_large'
  | 'building_wide'
  | 'shrub_small'
  | 'shrub_medium'
  | 'shrub_large'
  | 'tree_small'
  | 'kicker'
  | 'manual_pad'
  | 'pool'
  // Indoor office objects
  | 'wall_indoor'
  | 'ceiling_slab'
  | 'ceiling_panel'
  | 'fluorescent_light'
  | 'filing_cabinet'
  | 'printer'
  | 'exit_sign'
  | 'building_large';

export interface LevelObject {
  type: ObjectType;
  position: [number, number, number];
  rotation?: [number, number, number]; // Euler angles in degrees
  scale?: [number, number, number];
  params?: Record<string, unknown>; // Type-specific parameters
}

export interface SpawnPoint {
  position: [number, number, number];
  rotation: number; // Y rotation in degrees
}

export interface CollectiblePlacement {
  type: 'money' | 'document' | 'special';
  position: [number, number, number];
  value?: number;
}

export interface GoalDefinition {
  type: 'score' | 'collect' | 'combo' | 'grind' | 'escape' | 'time';
  target: number;
  description: string;
  reward?: number;
}

export interface LevelData {
  id: string;
  chapter: number;
  name: string;
  subtitle?: string;
  description: string;
  
  // Environment settings
  skyColor: string;
  skyColorTop?: string;
  skyColorBottom?: string;
  fogColor: string;
  fogNear: number;
  fogFar: number;
  ambientLight: number;
  sunIntensity: number;
  
  // Ground settings
  groundSize: number;
  groundTexture?: string;
  groundColor?: string;
  
  // Spawn and boundaries
  spawnPoint: SpawnPoint;
  bounds: {
    minX: number;
    maxX: number;
    minZ: number;
    maxZ: number;
  };
  
  // Level objects
  objects: LevelObject[];
  
  // Collectibles
  collectibles?: CollectiblePlacement[];
  
  // Goals/Objectives
  goals: GoalDefinition[];
  
  // Time limit (0 = no limit)
  timeLimit: number;
  
  // Music track
  music?: string;
  
  // Story elements
  introDialogue?: string[];
  outroDialogue?: string[];
}

// ===========================================
// LEVEL DEFINITIONS
// ===========================================

export const LEVELS: LevelData[] = [
  // =========================================
  // CHAPTER 1: THE ESCAPE
  // =========================================
  {
    id: 'ch1_office',
    chapter: 1,
    name: 'Cubicle Chaos',
    subtitle: 'The Great Escape Begins',
    description: 'Navigate through the open office floor as SEC agents close in!',
    
    skyColor: '#87CEEB',
    skyColorTop: '#1e90ff',
    skyColorBottom: '#87CEEB',
    fogColor: '#a0a0a0',
    fogNear: 30,
    fogFar: 100,
    ambientLight: 0.5,
    sunIntensity: 0.8,
    
    groundSize: 50,
    groundColor: '#6b5f4c',

    spawnPoint: {
      position: [0, 0.5, 0],
      rotation: 0
    },

    bounds: {
      minX: -24,
      maxX: 24,
      minZ: -24,
      maxZ: 24
    },

    // The floor plan — hallways, break room, boardroom, cubicle farm, server room, corner
    // offices, the stair set, the lift and the mezzanine deck — is generated by
    // src/world/OfficeLevel.ts (buildOfficeInterior). Read the header of that file first.
    //
    // What is left here is the loose skate furniture staged in the HALLWAYS, which is the one
    // thing the generated plan deliberately leaves empty:
    //   spine   (|x| < 8)   rails and kickers, both directions
    //   cross   (|z| < 4)   a floor rail in each arm
    //   loop    (|x| or |z| > 17)  one rail and two kickers
    //
    // NOTHING IS STAGED IN THE NORTH SPINE BETWEEN z = 6 AND z = 16 ANY MORE: that is where
    // the stair flight and the lift shaft now stand, and a floor rail through a staircase is
    // a run-ender. The old 'stairs' object at z = 20 is gone for the same reason — the level
    // has a real 14-tread flight now, and two staircases 4 m apart is one too many.
    objects: [
      // Floor rails down the south spine, one lane inboard of the ledge runs, so the player
      // can transfer ledge -> rail -> ledge without touching the carpet.
      { type: 'rail', position: [-4.0, 0, -13.5], rotation: [0, 90, 0], params: { length: 16 } },
      { type: 'rail', position: [4.0, 0, -13.5], rotation: [0, 90, 0], params: { length: 16 } },

      // Hallway rails: one down the north hallway, one down the west hallway. These are what
      // make the perimeter loop a grind line as well as a speed corridor.
      { type: 'rail', position: [0.0, 0, 20.0], rotation: [0, 0, 0], params: { length: 16 } },
      { type: 'rail', position: [-20.0, 0, 9.0], rotation: [0, 90, 0], params: { length: 14 } },

      // A rail in each arm of the cross hall, offset from the kicker lane.
      { type: 'rail', position: [13.0, 0, -2.6], rotation: [0, 0, 0], params: { length: 11 } },
      { type: 'rail', position: [-13.0, 0, 2.6], rotation: [0, 0, 0], params: { length: 11 } },

      // Kickers facing ALONG the spine, each with a landing run and a rail to transfer onto.
      { type: 'ramp', position: [2.4, 0, -8.5], rotation: [0, 180, 0] },
      { type: 'ramp', position: [2.4, 0, -13.0], rotation: [0, 0, 0] },

      // ...and a pair in the east hallway, facing along it.
      { type: 'ramp', position: [20.0, 0, -8.0], rotation: [0, 90, 0] },
      { type: 'ramp', position: [20.0, 0, -13.0], rotation: [0, 270, 0] },

      // Water coolers: DELIBERATELY NOT HERE ANY MORE.
      //
      // They were spawned twice. GoalSystem's "Smash both water coolers" publishes smash targets
      // at exactly these two positions, and Game.spawnDestructibles builds a knockable coolers
      // there — so these entries only ever added a SECOND, immovable one inside it, because
      // createLevelObject('water_cooler') makes a static physics box.
      //
      // They sit 0.6 m from the spine floor rails at |x| = 4.0, and the chair is a 0.4 m capsule:
      // a run holding that rail overlaps the box every time. Measured in tools/play.mjs: 13.9 m/s
      // to 0.0 m/s in one frame at (-4.5, -6.0), and the 13-trick line it was carrying cashed out.
      // The knockable versions still stand here, still complete the goal, and now they do what a
      // water cooler in a Tony Hawk level is supposed to do — go flying.

      // Fun box in the south spine, between the two ledge runs and the end quarter pipe.
      { type: 'fun_box', position: [0, 0, -18], params: { width: 7, depth: 4, height: 0.8 } },
    ],

    collectibles: [
      { type: 'document', position: [-4.2, 1, -10], value: 100 },
      { type: 'document', position: [4.2, 1, -10], value: 100 },
      // Up on the mezzanine deck (4.20 m), on the promenade: you have to get upstairs for it.
      { type: 'document', position: [0, 5.0, 8.0], value: 250 },
      { type: 'money', position: [-3, 1, 0], value: 500 },
      { type: 'money', position: [3, 1, 0], value: 500 },
    ],
    
    goals: [
      { type: 'score', target: 5000, description: 'Score 5,000 points', reward: 1000 },
      { type: 'grind', target: 3, description: 'Grind 3 desk rails', reward: 500 },
      { type: 'collect', target: 5, description: 'Collect all shredded documents', reward: 2000 },
    ],
    
    timeLimit: 120,
    
    introDialogue: [
      "SEC AGENT: We have a warrant for Tony Stonks!",
      "TONY: Time to roll! Literally!",
      "OBJECTIVE: Escape through the office before they catch you!"
    ]
  },
  
  // =========================================
  // CHAPTER 2: PARKING GARAGE
  // =========================================
  {
    id: 'ch1_garage',
    chapter: 1,
    name: 'Parking Lot Panic',
    subtitle: 'Underground Getaway',
    description: 'Shred through the parking garage to reach your getaway vehicle!',
    
    skyColor: '#333333',
    skyColorTop: '#1a1a2e',
    skyColorBottom: '#333333',
    fogColor: '#222222',
    fogNear: 20,
    fogFar: 80,
    ambientLight: 0.3,
    sunIntensity: 0.2,
    
    groundSize: 100,
    groundColor: '#444444',
    
    spawnPoint: {
      position: [0, 0.5, -40],
      rotation: 0
    },
    
    bounds: {
      minX: -45,
      maxX: 45,
      minZ: -45,
      maxZ: 45
    },
    
    objects: [
      // Car rows (obstacles and grind surfaces)
      { type: 'car', position: [-20, 0, -30], rotation: [0, 0, 0] },
      { type: 'car', position: [-20, 0, -20], rotation: [0, 0, 0] },
      { type: 'car', position: [-20, 0, -10], rotation: [0, 0, 0] },
      { type: 'car', position: [-20, 0, 0], rotation: [0, 0, 0] },
      
      { type: 'car', position: [20, 0, -30], rotation: [0, 180, 0] },
      { type: 'car', position: [20, 0, -20], rotation: [0, 180, 0] },
      { type: 'car', position: [20, 0, -10], rotation: [0, 180, 0] },
      { type: 'car', position: [20, 0, 0], rotation: [0, 180, 0] },
      
      // Concrete barriers (rails)
      { type: 'rail', position: [0, 0, -35], params: { length: 30 } },
      { type: 'rail', position: [0, 0, -15], params: { length: 30 } },
      { type: 'rail', position: [0, 0, 5], params: { length: 30 } },
      
      // Ramps
      { type: 'ramp', position: [-10, 0, 25], rotation: [0, 0, 0] },
      { type: 'ramp', position: [10, 0, 25], rotation: [0, 0, 0] },
      
      // Quarter pipes at edges
      { type: 'quarter_pipe', position: [-40, 0, 0], rotation: [0, 90, 0] },
      { type: 'quarter_pipe', position: [40, 0, 0], rotation: [0, -90, 0] },
      
      // Cones and barriers
      { type: 'cone', position: [-5, 0, 30] },
      { type: 'cone', position: [0, 0, 30] },
      { type: 'cone', position: [5, 0, 30] },
      { type: 'barrier', position: [0, 0, 35], params: { length: 10 } },
    ],
    
    goals: [
      { type: 'score', target: 10000, description: 'Score 10,000 points', reward: 2000 },
      { type: 'combo', target: 5000, description: 'Land a 5,000 point combo', reward: 1500 },
      { type: 'escape', target: 1, description: 'Reach the exit ramp', reward: 3000 },
    ],
    
    timeLimit: 180,
  },
  
  // =========================================  
  // CHAPTER 3: DOWNTOWN
  // =========================================
  {
    id: 'ch2_downtown',
    chapter: 2,
    name: 'Street Smart',
    subtitle: 'Urban Jungle',
    description: 'Hit the streets and show off your skills while evading pursuit!',
    
    skyColor: '#6699CC',
    skyColorTop: '#4a90d9',
    skyColorBottom: '#87ceeb',
    fogColor: '#888888',
    fogNear: 40,
    fogFar: 150,
    ambientLight: 0.6,
    sunIntensity: 1.0,
    
    groundSize: 150,
    groundColor: '#333333',
    
    spawnPoint: {
      position: [0, 0.5, -60],
      rotation: 0
    },
    
    bounds: {
      minX: -70,
      maxX: 70,
      minZ: -70,
      maxZ: 70
    },
    
    objects: [
      // Benches (grindable)
      { type: 'bench', position: [-15, 0, -40] },
      { type: 'bench', position: [-15, 0, -20] },
      { type: 'bench', position: [-15, 0, 0] },
      { type: 'bench', position: [15, 0, -40] },
      { type: 'bench', position: [15, 0, -20] },
      { type: 'bench', position: [15, 0, 0] },
      
      // Planters (obstacles)
      { type: 'planter', position: [-30, 0, -30] },
      { type: 'planter', position: [30, 0, -30] },
      { type: 'planter', position: [-30, 0, 30] },
      { type: 'planter', position: [30, 0, 30] },
      
      // Handrails on stairs
      { type: 'stairs', position: [0, 0, -50], params: { steps: 8 } },
      { type: 'rail', position: [-3, 0, -50], params: { length: 10 }, rotation: [15, 0, 0] },
      { type: 'rail', position: [3, 0, -50], params: { length: 10 }, rotation: [15, 0, 0] },
      
      // Half pipe in plaza
      { type: 'half_pipe', position: [0, 0, 30], params: { width: 15, length: 20 } },
      
      // Trash cans
      { type: 'trash_can', position: [-25, 0, 0] },
      { type: 'trash_can', position: [25, 0, 0] },
    ],
    
    goals: [
      { type: 'score', target: 25000, description: 'Score 25,000 points', reward: 5000 },
      { type: 'combo', target: 10000, description: 'Land a 10,000 point combo', reward: 3000 },
      { type: 'grind', target: 10, description: 'Grind 10 rails', reward: 2000 },
      { type: 'time', target: 120, description: 'Survive for 2 minutes', reward: 2500 },
    ],
    
    timeLimit: 180,
  }
];

// Import story levels
import { STORY_LEVELS, StoryLevelData } from '../story/StoryLevels';

// Combined level getter (checks both free skate and story levels)
export function getLevelById(id: string): LevelData | undefined {
  // Check free skate levels first
  const freeSkateLevel = LEVELS.find(level => level.id === id);
  if (freeSkateLevel) return freeSkateLevel;
  
  // Check story levels
  const storyLevel = STORY_LEVELS.find(level => level.id === id);
  if (storyLevel) return storyLevel as LevelData;
  
  return undefined;
}

// Get story level with extra properties
export function getStoryLevel(id: string): StoryLevelData | undefined {
  return STORY_LEVELS.find(level => level.id === id);
}

// Get levels by chapter (free skate only)
export function getLevelsByChapter(chapter: number): LevelData[] {
  return LEVELS.filter(level => level.chapter === chapter);
}

// Get all chapter numbers
export function getChapters(): number[] {
  return [...new Set(LEVELS.map(level => level.chapter))].sort();
}

// Get all free skate levels
export function getFreeSkakeLevels(): LevelData[] {
  return LEVELS;
}

// Get all story levels
export function getAllStoryLevels(): StoryLevelData[] {
  return STORY_LEVELS;
}

// Re-export story types
export type { StoryLevelData, StoryCheckpoint } from '../story/StoryLevels';
