/**
 * Goal placements for Cubicle Chaos, DERIVED from the skate layout rather than typed in.
 *
 * The ground floor is generated by tools/levelsim (see CubicleChaosLayout.ts). Hard-coded goal
 * coordinates went stale the moment the layout changed — letters floating over empty carpet,
 * gaps between kickers that no longer exist. Everything here is computed from the layout, so
 * a re-optimised layout keeps a checklist that still walks you through its lines.
 */
import { CUBICLE_CHAOS_LAYOUT, type SkateItem } from './CubicleChaosLayout';
import { inSkateLane } from './SkateLayoutUtil';

type V3 = [number, number, number];
const L = CUBICLE_CHAOS_LAYOUT;
const fwd = (it: SkateItem, d: number, y: number): V3 => [it.x + Math.sin(it.yaw) * d, y, it.z + Math.cos(it.yaw) * d];
const r1 = (v: number) => Math.round(v * 10) / 10;
const rv = (p: V3): V3 => [r1(p[0]), r1(p[1]), r1(p[2])];

/**
 * Where on (or over) a feature a pickup belongs: in the arc you fly or on the line you ride.
 * Heights are what GoalSystem stores; Game.spawnCollectibles draws the ring 1.1 m above that
 * and collects within 2.6 m of the chair's centre (0.7 m up when rolling).
 */
function pickupSpot(it: SkateItem): V3 {
  switch (it.type) {
    case 'kicker': return fwd(it, it.hd + 3.5, 1.5);        // at the top of the kicker air
    case 'qp': return fwd(it, it.hd - 0.4, 2.4);            // above the coping: vert only
    case 'rail': case 'ledge': return fwd(it, 0, it.h * 0.9);
    case 'pad': return fwd(it, 0, 0.4);
    default: return fwd(it, 0, 1.0);                         // over the table: ollie it
  }
}

/** Features ordered around the plate, so consecutive letters form a loop, not a zig-zag. */
const loop = [...L].sort((a, b) => Math.atan2(a.x, a.z) - Math.atan2(b.x, b.z));

/** S-T-O-N-K-S: six features spread evenly round that loop. */
export const OFFICE_LETTERS: V3[] = Array.from({ length: 6 }, (_, i) =>
  rv(pickupSpot(loop[Math.floor((i * loop.length) / 6) % loop.length])));

/** Every kicker's air is a named gap; so is every quarter pipe's. */
export const OFFICE_GAPS = [
  ...L.filter((it) => it.type === 'kicker').map((it, i) => ({
    id: `kicker_air_${i}`, name: i === 0 ? 'Kicker Air' : `Kicker Air ${i + 1}`, bonus: 600,
    from: rv(fwd(it, 0, 0)), to: rv(fwd(it, it.hd + 8, 0)), radius: 3.2,
  })),
  ...L.filter((it) => it.type === 'qp').map((it, i) => ({
    id: `qp_air_${i}`, name: i === 0 ? 'Office Vert' : `Office Vert ${i + 1}`, bonus: 800,
    from: rv(fwd(it, -it.hd - 3, 0)), to: rv(fwd(it, -it.hd - 3, 0)), radius: 3.5,
  })),
];

/**
 * The two water coolers: close to a line (so you pass them) but never in one (so they are a
 * choice, not a wall). First two grid points 1.5-4 m from a feature and outside every lane.
 */
function coolerSpots(): V3[] {
  const out: V3[] = [];
  for (let z = -18; z <= 18 && out.length < 2; z += 1.5) {
    for (let x = -18; x <= 18 && out.length < 2; x += 1.5) {
      if (inSkateLane(L, x, z, 1.2)) continue;
      const near = L.some((it) => Math.hypot(it.x - x, it.z - z) < Math.max(it.hw, it.hd) + 4);
      if (!near) continue;
      if (out.some((p) => Math.hypot(p[0] - x, p[2] - z) < 12)) continue;
      out.push([x, 0, z]);
    }
  }
  return out;
}
export const OFFICE_COOLERS: V3[] = coolerSpots();

/** Shredded documents and petty cash strung along the grinds and pads. */
export const OFFICE_CASH = L.filter((it) => it.type === 'rail' || it.type === 'ledge' || it.type === 'pad')
  .slice(0, 5).map((it, i) => {
    // Halfway down the line from the letter spot, so a letter and a document never share a place.
    const p = pickupSpot(it); const d = it.hd * 0.55;
    return { pos: rv([p[0] + Math.sin(it.yaw) * d, p[1], p[2] + Math.cos(it.yaw) * d]), value: i < 3 ? 100 + 75 * i : 500 };
  });

/** The secret file: high over the far end of the longest grind — you get it by riding it out. */
export const OFFICE_HIDDEN: V3 = (() => {
  const grinds = L.filter((it) => it.type === 'rail' || it.type === 'ledge');
  const g = grinds.sort((a, b) => b.hd - a.hd)[0];
  return g ? rv(fwd(g, g.hd + 1.2, g.h + 2.4)) : [0, 3, 0];   // out of reach until you pop off the end
})();
