/**
 * Write an optimised levelsim layout out as src/world/CubicleChaosLayout.ts.
 * usage: node tools/levelsim/to-ts.mjs best.json baseline-metrics.json > src/world/CubicleChaosLayout.ts
 */
import { readFileSync } from 'node:fs';
const L = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const base = process.argv[3] ? JSON.parse(readFileSync(process.argv[3], 'utf8')) : null;
const m = L.metrics;
const r = (v, n = 2) => +(+v).toFixed(n);
const items = L.items.filter((it) => !it.fixed);
const rows = [
  ['score (objective)', 'score'], ['tricks / min', 'tricksPerMin'], ['weighted tricks / min', 'weightedTricksPerMin'],
  ['airs / min (kicker, QP, gap)', 'airPerMin'], ['time inside a combo', 'comboShare'], ['longest combo, s (mean)', 'meanLongestCombo'],
  ['collisions / min', 'collisionsPerMin'], ['hard hits / min', 'hardHitsPerMin'], ['bad landings / min', 'badLandPerMin'],
  ['floor with 3 m of clearance', 'open3'], ['mean clearance, m', 'meanClear'], ['features ever used', 'featureUse'],
];
const table = rows.map(([label, k]) => ` *   ${label.padEnd(30)} ${String(base ? r(base[k]) : '').padStart(8)}  ${String(r(m[k])).padStart(8)}`).join('\n');
console.log(`/**
 * CUBICLE CHAOS — ground-floor skate layout. GENERATED by tools/levelsim/optimize.mjs; do not
 * hand-edit positions without re-scoring (node tools/levelsim/eval.mjs).
 *
 * Axes: x across, z along, yaw = atan2(dx, dz). hw/hd are half-extents along the item's local
 * x / z. Local +z is the direction you ride OFF a kicker, ALONG a rail or ledge, and INTO a
 * quarter pipe. The stairs and lift are fixed architecture and are not listed here.
 *
 * levelsim, 64 players x 60 s (half pure swervers, half lining up what they see):
 *                                    previous      this
${table}
 */

export type SkateItemType = 'kicker' | 'rail' | 'ledge' | 'pad' | 'qp' | 'block';

export interface SkateItem {
  type: SkateItemType;
  x: number;
  z: number;
  yaw: number;
  hw: number;
  hd: number;
  h: number;
}

export const CUBICLE_CHAOS_LAYOUT: readonly SkateItem[] = [
${items.map((it) => `  { type: '${it.type}', x: ${r(it.x)}, z: ${r(it.z)}, yaw: ${r(it.yaw, 4)}, hw: ${r(it.hw)}, hd: ${r(it.hd)}, h: ${r(it.h)} },`).join('\n')}
];`);
